# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 10:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import team.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0004_auto_20180321_0327'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', team.fields.ThumbnailImageField(upload_to='team/%Y/%m')),
                ('description', models.TextField(blank=True, verbose_name='Photo Description')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AlterModelOptions(
            name='planpost',
            options={'ordering': ['modify_date'], 'verbose_name': 'planpost', 'verbose_name_plural': 'planposts'},
        ),
        migrations.AddField(
            model_name='planphoto',
            name='planpost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.PlanPost'),
        ),
    ]
