# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 05:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20180321_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planphoto',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='planphoto',
            name='planpost',
        ),
        migrations.RemoveField(
            model_name='planpost',
            name='owner',
        ),
        migrations.DeleteModel(
            name='PlanPhoto',
        ),
        migrations.DeleteModel(
            name='PlanPost',
        ),
    ]
